apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        version: "0.1.12"
    spec:
      containers:
      - image:  "quay.io/swade1987/hello-world:0.1.12"
        name: hello-world
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  NAME
          value:  World
        - name:  VERSION
          value:  "0.1.12"
        - name:  MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath:  metadata.name
        - name:  MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath:  metadata.namespace
        - name:  MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath:  status.podIP
        - name:  HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath:  spec.nodeName
        ports:
        - containerPort:  8080
          name: hello-world
      restartPolicy: Always